name: Fetch ICON-D2 GRIB2 and Generate PNGs

on:
  workflow_dispatch:

jobs:
  fetch_generate_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.GH_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set RUN and DATE (fixed)
        id: set_run_date
        run: |
          DATE="2025-10-05"
          RUN="16"

          echo "RUN=$RUN" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Download t2m GRIB2 files
        run: |
          mkdir -p data/t2m
          cd data/t2m
          seq 0 1 | xargs -n 1 -P 7 -I{} bash -c '
            i_padded=$(printf "%03d" {})
            URL="https://opendata.dwd.de/weather/nwp/v1/m/icon-d2-ruc/p/T_2M/r/${DATE}T${RUN}:00/s/PT${i_padded}H00M.grib2"
            wget -O t2m_${i_padded}.grib2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
          '

      - name: Download ww GRIB2 files
        run: |
          mkdir -p data/ww
          cd data/ww
          seq 1 2 | xargs -n 1 -P 7 -I{} bash -c '
            i_padded=$(printf "%03d" {})
            URL="https://opendata.dwd.de/weather/nwp/v1/m/icon-d2-ruc/p/WW/r/${DATE}T${RUN}:00/s/PT${i_padded}H00M.grib2"
            wget -O ww_${i_padded}.grib2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
          '

      - name: Download tp GRIB2 files
        run: |
          mkdir -p data/tp
          cd data/tp
          seq 0 1 | xargs -n 1 -P 7 -I{} bash -c '
            i_padded=$(printf "%03d" {})
            URL="https://opendata.dwd.de/weather/nwp/v1/m/icon-d2-ruc/p/TOT_PREC_D/r/${DATE}T${RUN}:00/s/PT${i_padded}H00M.grib2"
            wget -O tot_prec_${i_padded}.grib2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
          '

      - name: Generate PNGs
        run: |
          mkdir -p iconruc/${RUN}/t2m
          mkdir -p iconruc/${RUN}/ww
          mkdir -p iconruc/${RUN}/tp

          python scripts/generate_pngs.py data/t2m iconruc/${RUN}/t2m t2m
          python scripts/generate_pngs.py data/ww iconruc/${RUN}/ww ww
          python scripts/generate_pngs.py data/tp iconruc/${RUN}/tp tp

      - name: Delete GRIB2 files
        run: rm -rf data/

      - name: Commit and push generated PNGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add iconruc/${RUN}
          git commit -m "Add ICON-RUC PNGs for run ${RUN}" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
