name: Fetch ICON-RUC GRIB2 and Generate PNGs

on:
  workflow_dispatch:

jobs:
  set_run_date:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.set_run_date_step.outputs.run }}
      date: ${{ steps.set_run_date_step.outputs.date }}
    steps:
      - name: Set RUN and DATE
        id: set_run_date_step
        run: |
          HOUR=$(date -u +%H)
          DATE=$(date -u +%Y-%m-%d)
          RUN=$HOUR

          echo "RUN=$RUN" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV

          echo "run=$RUN" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

          echo "Current UTC time: $HOUR -> RUN=$RUN, DATE=$DATE"

  t2m_job:
    runs-on: ubuntu-latest
    needs: set_run_date
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download GRID
        run: |
          mkdir -p data/grid
          wget -q http://icon-downloads.mpimet.mpg.de/grids/public/edzw/icon_grid_0047_R19B07_L.nc -O data/grid/grid.nc

      - name: Download t2m GRIB2
        run: |
          mkdir -p data/t2m
          cd data/t2m
          seq 0 13 | xargs -n 1 -P 4 -I{} bash -c '
            i_padded=$(printf "%03d" {} )
            URL="https://opendata.dwd.de/weather/nwp/v1/m/icon-d2-ruc/p/T_2M/r/${{ needs.set_run_date.outputs.date }}T${{ needs.set_run_date.outputs.run }}:00/s/PT${i_padded}H00M.grib2"
            wget -q -O t2m_${i_padded}.grib2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
          '

      - name: Generate PNGs
        run: |
          mkdir -p iconruc/${{ needs.set_run_date.outputs.run }}/t2m
          python scripts/generate_pngs.py data/t2m iconruc/${{ needs.set_run_date.outputs.run }}/t2m t2m data/grid/grid.nc

      - name: Upload t2m artifact
        uses: actions/upload-artifact@v4
        with:
          name: iconruc-t2m
          path: iconruc/${{ needs.set_run_date.outputs.run }}/t2m

  ww_job:
    runs-on: ubuntu-latest
    needs: set_run_date
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download GRID
        run: |
          mkdir -p data/grid
          wget -q http://icon-downloads.mpimet.mpg.de/grids/public/edzw/icon_grid_0047_R19B07_L.nc -O data/grid/grid.nc
      - name: Download ww GRIB2
        run: |
          mkdir -p data/ww
          cd data/ww
          seq 1 14 | xargs -n 1 -P 4 -I{} bash -c '
            i_padded=$(printf "%03d" {} )
            URL="https://opendata.dwd.de/weather/nwp/v1/m/icon-d2-ruc/p/WW/r/${{ needs.set_run_date.outputs.date }}T${{ needs.set_run_date.outputs.run }}:00/s/PT${i_padded}H00M.grib2"
            wget -q -O ww_${i_padded}.grib2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
          '
      - name: Generate PNGs
        run: |
          mkdir -p iconruc/${{ needs.set_run_date.outputs.run }}/ww
          python scripts/generate_pngs.py data/ww iconruc/${{ needs.set_run_date.outputs.run }}/ww ww data/grid/grid.nc
      - name: Upload ww artifact
        uses: actions/upload-artifact@v4
        with:
          name: iconruc-ww
          path: iconruc/${{ needs.set_run_date.outputs.run }}/ww

  tp_job:
    runs-on: ubuntu-latest
    needs: set_run_date
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download GRID
        run: |
          mkdir -p data/grid
          wget -q http://icon-downloads.mpimet.mpg.de/grids/public/edzw/icon_grid_0047_R19B07_L.nc -O data/grid/grid.nc
      - name: Download tp GRIB2
        run: |
          mkdir -p data/tp
          cd data/tp
          seq 0 13 | xargs -n 1 -P 4 -I{} bash -c '
            i_padded=$(printf "%03d" {} )
            URL="https://opendata.dwd.de/weather/nwp/v1/m/icon-d2-ruc/p/TOT_PREC_D/r/${{ needs.set_run_date.outputs.date }}T${{ needs.set_run_date.outputs.run }}:00/s/PT${i_padded}H00M.grib2"
            wget -q -O tot_prec_${i_padded}.grib2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
          '
      - name: Generate PNGs
        run: |
          mkdir -p iconruc/${{ needs.set_run_date.outputs.run }}/tp
          python scripts/generate_pngs.py data/tp iconruc/${{ needs.set_run_date.outputs.run }}/tp tp data/grid/grid.nc
      - name: Upload tp artifact
        uses: actions/upload-artifact@v4
        with:
          name: iconruc-tp
          path: iconruc/${{ needs.set_run_date.outputs.run }}/tp

  dbz_cmax_job:
    runs-on: ubuntu-latest
    needs: set_run_date
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download GRID
        run: |
          mkdir -p data/grid
          wget -q http://icon-downloads.mpimet.mpg.de/grids/public/edzw/icon_grid_0047_R19B07_L.nc -O data/grid/grid.nc
      - name: Download dbz_cmax GRIB2
        run: |
          mkdir -p data/dbz_cmax
          cd data/dbz_cmax
          seq 0 13 | xargs -n 1 -P 4 -I{} bash -c '
            i_padded=$(printf "%03d" {} )
            URL="https://opendata.dwd.de/weather/nwp/v1/m/icon-d2-ruc/p/DBZ_CMAX/r/${{ needs.set_run_date.outputs.date }}T${{ needs.set_run_date.outputs.run }}:00/s/PT${i_padded}H00M.grib2"
            wget -q -O dbz_cmax_${i_padded}.grib2 "$URL" || echo "Datei $URL nicht verfügbar, überspringe..."
          '
      - name: Generate PNGs
        run: |
          mkdir -p iconruc/${{ needs.set_run_date.outputs.run }}/dbz_cmax
          python scripts/generate_pngs.py data/dbz_cmax iconruc/${{ needs.set_run_date.outputs.run }}/dbz_cmax dbz_cmax data/grid/grid.nc
      - name: Upload dbz_cmax artifact
        uses: actions/upload-artifact@v4
        with:
          name: iconruc-dbz_cmax
          path: iconruc/${{ needs.set_run_date.outputs.run }}/dbz_cmax

  deploy_to_r2:
    needs: [t2m_job, ww_job, tp_job, dbz_cmax_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download all PNG artifacts
        uses: actions/download-artifact@v4
        with:
          name: iconruc-t2m
          path: iconruc/t2m
      - uses: actions/download-artifact@v4
        with:
          name: iconruc-ww
          path: iconruc/ww
      - uses: actions/download-artifact@v4
        with:
          name: iconruc-tp
          path: iconruc/tp
      - uses: actions/download-artifact@v4
        with:
          name: iconruc-dbz_cmax
          path: iconruc/dbz_cmax

      - name: Generate Metadata
        run: |
          python scripts/generate_metadata.py iconruc/${{ needs.set_run_date.outputs.run }} ${{ needs.set_run_date.outputs.run }} ${{ env.DATE }}

      - name: Clean old runs on R2 except current
        run: |
          for run_folder in $(aws s3 ls s3://${{ secrets.R2_BUCKET }}/icon-ruc/ --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com | awk '{print $2}' | sed 's#/##'); do
            if [ "$run_folder" != "${{ needs.set_run_date.outputs.run }}/" ]; then
              aws s3 rm s3://${{ secrets.R2_BUCKET }}/icon-ruc/$run_folder --recursive --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
            fi
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

      - name: Upload current run and metadata.json to R2
        run: |
          aws s3 sync ./iconruc/${{ needs.set_run_date.outputs.run }}/ s3://${{ secrets.R2_BUCKET }}/icon-ruc/${{ needs.set_run_date.outputs.run }}/ \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          aws s3 cp ./iconruc/metadata.json s3://${{ secrets.R2_BUCKET }}/icon-ruc/metadata.json \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
